spring:
  application:
    name: nacos-provider-two
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: 0
  datasource:
    url: jdbc:mysql://localhost:3306/root?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
---
server:
  port: 5000
spring:
  profiles: 0
---
server:
  port: 5001
spring:
  profiles: 1

