spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: 0

---
server:
  port: 5000
spring:
  profiles: 0
---
server:
  port: 5001
spring:
  profiles: 1

