spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos server的地址
        enabled: false
      config:
        file-extension: yaml
        enabled: true
    sentinel:
      enabled: false
      filter:
        enabled: false
#      transport:
#        dashboard: 127.0.0.1:8080
#        port: 8719
#        #sentinel 中限流和降级的规则，必须持久化，不然重启就失效了。主要有
#        # private FileDataSourceProperties file;
#        #    private NacosDataSourceProperties nacos;  需要增加nacos和sentinel持久化的依赖
#        #    private ZookeeperDataSourceProperties zk;
#        #    private ApolloDataSourceProperties apollo;
#        #    private RedisDataSourceProperties redis;
#        #    private ConsulDataSourceProperties consul;
#      datasource:
#        ds:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            data-id: ${spring.application.name}-sentinel
#            rule-type: flow  # 类型来自RuleType类
#        degrade:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            data-id: ${spring.application.name}-sentinel-degrade
#            rule-type: degrade  # 类型来自RuleType类
#      eager: true

server:
  port: 6000
logging:
  level:
   com.xs: debug