server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dianlan?characterEncoding=utf-8&useSSL=false
    password: xueshuai0922
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:

    database: 0
    timeout: 1000 #read 超时时间1000ms
    password: xueshuai123
    sentinel:
      nodes: 118.190.141.119:26379
      master: mymaster
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制



mybatis:
  mapper-locations: classpath:xmls/*Mapper.xml
logging:
  level:
    com:
      xs:
        debug
#redis 设置
