


#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/root?useUnicode=true&characterEncoding=UTF-8


#mybatis配置
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 增加日志输出
mybatis:
  type-aliases-package: com.xs.mybatis
  configuration:
    object-factory: com.xs.mybatis.login.entity.UserBeanFactory
server:
  port: 8080
pagehelper:
  default-count: false