spring:
    redis:
        port: 6379
        host: 172.17.1.50
        cluster:
            max-redirects: 3
            nodes:
                - 172.17.1.50:6381
                - 172.17.1.50:6382
                - 172.17.1.50:6383
                - 172.17.1.50:6384
                - 172.17.1.50:6385
                - 172.17.1.50:6386
        password: winning.2019

